### ISSUE TITLE
Do notation section

### ISSUE THREAD

**Issue by FayeAlephNil** [anchpop/wise_mans_haskell#1]
[spongebobDo.hs](https://github.com/anchpop/wise_mans_haskell/blob/master/haskelltests/should_compile/spongebobDo.hs) does not actually use do notation, which is rather confusing in reading. Likewise, [goodDo.hs](https://github.com/anchpop/wise_mans_haskell/blob/master/haskelltests/should_compile/goodDo.hs) uses `return` whereas the book uses `pure`, and it includes the error comment when it doesn't actually error

**Comment by anchpop** [comment]
Thanks! These issues should be fixed now
