### ISSUE TITLE
Illegal indentation on chapter "recursion practice"

### ISSUE THREAD

**Issue by stz-seongheon** [anchpop/wise_mans_haskell#11]
All the first lines are indented in this chapter
`!indent()` need to be removed, I guess.

[Link](https://github.com/anchpop/wise_mans_haskell/blob/54fffbce3164a737d20c64996dd5f42ae44fdc93/book.md#recursion-practice)

**Comment by anchpop** [comment]
should be fixed. The issue was the spaces before `!indent()`. Thanks!
