### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by javbit** [anchpop/wise_mans_haskell#2]
In case you forgot or didn't think of it, please add some sort of license.

A Creative Commons or some sort of documentation license would be applicable.

If you don't want a license that's cool too, but make it explicit.

**Comment by anchpop** [comment]
Thanks! I'll put one on the new website once it goes live

**Comment by samuelallan72** [comment]
Licensing information in the repo itself would also be good, so people are clear on the terms of use if they come across the source.

**Comment by anchpop** [comment]
Done
