### ISSUE TITLE
Discord link broken and typo

### ISSUE THREAD

**Issue by Tehnix** [anchpop/wise_mans_haskell#3]
It seems that the discord invite link in the beginning is expired. I don't know if there's a way to make it permanent?

Either way, I just wanted to report a type in your margin note _"However I that saying “everything is a function” is more intuitive."_ where you are missing I _think_ in "However I think...".

On a side-note, I agree that it helps with intuition :)

**Comment by anchpop** [comment]
Thanks! You should see these changes integrated on the new site, sometime
soon.

Discord invite link expiry seems to be very strange - even after selecting
"never expire", they still seem to expire sometimes. I'll update the link.
