### ISSUE TITLE
Typo in "data types with other values" section

### ISSUE THREAD

**Issue by stz-seongheon** [anchpop/wise_mans_haskell#8]
I just found the typo (broken code format), and maybe missing prelude error examples? It takes me some time to understand what can cause that error.

*****
[Link](https://github.com/anchpop/wise_mans_haskell/blob/063ef5b826d9d769f90c4325812f15e4ef0b7df3/book.md#data-types-with-other-values)

    ```haskell
    data Human = Human {name :: String}
    data Dog = Dog {name :: String}
    ```

**Comment by anchpop** [comment]
This was a formatting error, thanks for catching it!
